%YAML:1.0
# data
# the tum dataset directory, change it to yours! 
dataset_dir: /home/lyp/SLAM/codes/slambook/slambook/ch8/data
# camera intrinsics
# fr1
camera.fx: 517.3
camera.fy: 516.5
camera.cx: 325.1
camera.cy: 249.7

# fr2
#camera.fx: 520.9
#camera.fy: 521.0
#camera.cx: 325.1
#camera.cy: 249.7

camera.depth_scale: 5000

# VO Parameters
num_features: 500
scale: 1.2
level: 4
match_ratio: 2.0
max_lost: 10
min_inliers: 30
min_rot: 0.1
min_trans: 0.1
map_erase_ratio: 0.1
